// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Services.AirlineBookingManagement.DbContexts;

namespace Services.AirlineBookingManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Services.AirlineBookingManagement.Models.BookingDetails", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineID");

                    b.Property<string>("AirlineName");

                    b.Property<DateTime>("BookingDate");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("CreatedUserID");

                    b.Property<string>("Email");

                    b.Property<int>("FlightNumber");

                    b.Property<bool>("IsCancelled");

                    b.Property<bool>("MealOpted");

                    b.Property<string>("Name");

                    b.Property<int>("NoOfPassengers");

                    b.Property<string>("PNR");

                    b.Property<string>("PaymentStatus");

                    b.Property<string>("SeatType");

                    b.HasKey("BookingID");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("Services.AirlineBookingManagement.Models.BookingPassengerRelation", b =>
                {
                    b.Property<int>("RefID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int>("BookingRefNumber");

                    b.Property<string>("Gender");

                    b.Property<string>("PassengerName");

                    b.HasKey("RefID");

                    b.HasIndex("BookingRefNumber");

                    b.ToTable("PassengerDetails");
                });

            modelBuilder.Entity("Services.AirlineBookingManagement.Models.BookingSeatNoRelation", b =>
                {
                    b.Property<int>("RefID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookingNumber");

                    b.Property<int>("SeatNumber");

                    b.HasKey("RefID");

                    b.HasIndex("BookingNumber");

                    b.ToTable("BookingSeatNumberRelation");
                });

            modelBuilder.Entity("Services.AirlineBookingManagement.Models.BookingPassengerRelation", b =>
                {
                    b.HasOne("Services.AirlineBookingManagement.Models.BookingDetails", "BookingDetailsReference")
                        .WithMany()
                        .HasForeignKey("BookingRefNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Services.AirlineBookingManagement.Models.BookingSeatNoRelation", b =>
                {
                    b.HasOne("Services.AirlineBookingManagement.Models.BookingDetails", "BookingDetailsRef")
                        .WithMany()
                        .HasForeignKey("BookingNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
